# Generated by Django 5.2.1 on 2025-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('developer', 'Developer')], default='player', max_length=10),
        ),
    ]
