# Generated by Django 5.2.1 on 2025-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_earnings_total_game_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
