# Generated by Django 5.2.1 on 2025-08-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
