# Generated by Django 5.2.1 on 2025-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_reward',
            field=models.DateField(blank=True, null=True),
        ),
    ]
