# Generated by Django 5.2.1 on 2025-08-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_last_login_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='shop_offers/')),
                ('price', models.IntegerField()),
                ('offer_type', models.CharField(choices=[('background', 'Background'), ('reward', 'Reward')], default='reward', max_length=50)),
                ('css_class', models.CharField(blank=True, help_text='For backgrounds: name of CSS class to apply', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='active_background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shopoffer'),
        ),
    ]
