# Generated by Django 5.2.1 on 2025-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shopoffer_profile_active_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopoffer',
            name='css_class',
            field=models.CharField(blank=True, help_text='For backgrounds only: CSS class to apply', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_offers/'),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
