# Generated by Django 5.2.1 on 2025-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ownedoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.game'),
        ),
    ]
