# Generated by Django 5.2.1 on 2025-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_referral_code_profile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('frame', 'Frame Ad'), ('popup', 'Popup Ad')], default='frame', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(blank=True, choices=[('home', 'Home Page'), ('catalog', 'Catalog Page')], max_length=10, null=True),
        ),
    ]
